apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-meetup-quarkus
  labels:
    app.kubernetes.io/name: java-meetup-quarkus
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: java-meetup-quarkus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-meetup-quarkus
    spec:
      containers:
        - name: web
          image: jwnmulder/java-meetup-quarkus:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "64M"
            limits:
              memory: "256M"
