apiVersion: v1
kind: Service
metadata:
  name: java-meetup-quarkus-external
  labels:
    app.kubernetes.io/name: java-meetup-quarkus
spec:
  selector:
    app.kubernetes.io/name: java-meetup-quarkus
  type: NodePort
  ports:
    - name: http
      port: 8080
